server:
  servlet:
    context-path: /health-care
  port: 8000

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/db_healthcaresystem}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:090203Qu@n}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibrenate:
        connection:
          characterEncoding: utf8mb4
          useUnicode: true
          charset: UTF-8
    show-sql: true
    generate-ddl: true
    open-in-view: false

jwt:
  signerKey: "VRtbrMdCEtOoaaq9QlJ4Av+C2g2PT0QjwBILazmm9quzHK219ODpkjqMrVkoHRLI"
  validDuration: 36000 #in seconds.
  refreshableDuration: 36000 #in seconds.